-- DROP PROCEDURE IF EXISTS sp_get_latest_promotions_by_services;
-- CREATE PROCEDURE sp_get_latest_promotions_by_services(IN p_subscriber_id INT) BEGIN WITH latest_subs AS (
--     SELECT s.id AS subscription_id,
--         sv.id AS service_id,
--         ROW_NUMBER() OVER (
--             PARTITION BY CASE
--                 WHEN sv.id = 1 THEN 'service_1'
--                 ELSE CONCAT('service_', sv.id)
--             END
--             ORDER BY s.activation_date DESC
--         ) AS rn
--     FROM subscriptions s
--         JOIN plans p ON s.plan_id = p.id
--         JOIN services sv ON p.service_id = sv.id
--     WHERE sv.parent_id IS NULL
--         AND s.subscriber_id = p_subscriber_id
-- )
-- SELECT pd.*
-- FROM latest_subs ls
--     JOIN payments pay ON pay.subscription_id = ls.subscription_id
--     JOIN payment_detail pd ON pd.payment_id = pay.id
-- WHERE ls.rn = 1
--     AND pay.is_paid = 1;
-- END;
CALL sp_get_latest_promotions_by_services(12)