from app.controllers import *

from app.controllers.voucher_controller import voucher_bp
from app.controllers.service_controller import service_bp
from app.controllers.function_controller import function_bp
from app.controllers.subscription_controller import subscription_bp
from app.controllers.contract_controller import contract_bp
from app.controllers.country_controller import country_bp
from app.controllers.permissiondetail_controller import permission_bp
from app.controllers.account_controller import account_bp
from app.controllers.plan_controller import plan_bp
from app.controllers.rolegroup_controller import role_group_bp
from app.controllers.rolegroupdetail_controller import role_group_detail_bp
from app.controllers.usagelog_controller import usagelog_bp
from app.controllers.payment_controller import payment_bp
from app.controllers.paymentdetail_controller import payment_detail_bp
from app.controllers.staff_controller import staff_bp
from app.controllers.customer_controller import customer_bp
from app.controllers.plandetail_controller import plan_detail_bp
from app.controllers.plannetwork_controller import plan_network_bp
from app.controllers.network_controller import network_bp
from app.controllers.country_controller import country_bp
from app.controllers.home_controller import main_bp
from app.controllers.admin_home_controller import admin_main_bp
from app.controllers.api_payments import payment_api_bp
